# -*- coding: utf-8 -*-
"""GearBox Faliure Data_Deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hm3xMUMoxKs_UOI0XgGj3IlS1UL-H2Lb
"""



# import libraries

import numpy as np
import joblib
import streamlit as st

# gearbox_failure_preiction.pkl

model = joblib.load('gearbox_failure_preiction.pkl')

st.set_page_config(page_title='Gear Box Failure Classification', layout = "centered")
st.title('Gear Box Failure Classification App')
st.write('Predict whether the Failure Rate')

Load = st.number_input('value of Load_% ', value = None)
Temperature_C	= st.number_input('value of Temperature_C ', value = None)
Vibration_mm_s	= st.number_input('value of Vibration_mm_s ', value = None)
Oil_Level =	st.number_input('value of Oil_Level_% ', value = None)

if st.button('Predict'):
  input_data = np.array([[
      Load_,
      Temperature_C,
      Vibration_mm_s,
      Oil_Level,
  ]])
  prediction = model.predict(input_data)[0]
  if prediction == 0:
    st.success('Fail')
  else:
    st.success('Pass')







